### ISSUE TITLE
可不可规定日期范围

### ISSUE THREAD

**Issue by zshno1** [AFAP/XCX-Plugins#1]
日历上展示日期区间可以选择为黑色， 超出日期区间可以展示为灰色

**Comment by AFAP** [comment]
可以的，这个其实改起来也比较简单，你可以把整体css里面的color改成灰色，然后在daysStyle这个属性里把你说的选中的日期加进去，然后设置color为你要的黑色，这个是支持设置每一天一个颜色的

**Comment by zshno1** [comment]
我可能表达的不太明白，我的意思是比如今天是11.4号 然后我想未来三个月的日期展示是黑色，其他的日期都是灰色

**Comment by zshno1** [comment]
可以了  我好想看明白 
Thank you

**Comment by zshno1** [comment]
可以了  我好像看明白了
Thank you

**Comment by AFAP** [comment]
> 可以了 我好像看明白了
> Thank you

这个方式就是得逐个加，不支持起止。不过走个循环获得下3个月的所有日期就行了。控件反正都是要下载下来的，css随意改😄

**Comment by AFAP** [comment]
已经没问题了。
