### ISSUE TITLE
希望传入一个数组【2019-12-03,2019-12-31】，让这段时间是整个区间选中的效果

### ISSUE THREAD

**Issue by candyAndBella** [AFAP/XCX-Plugins#3]

**Comment by AFAP** [comment]
是指pickerRange模式下，你要给定一个初始值吗？默认就是显示如：2019-12-03 至 2019-12-31这样？

**Comment by candyAndBella** [comment]
> 是指pickerRange模式下，你要给定一个初始值吗？默认就是显示如：2019-12-03 至 2019-12-31这样？

对，页面显示的就是2019年12月3号到12月31号，这段区间是选中状态。

**Comment by AFAP** [comment]
> > 是指pickerRange模式下，你要给定一个初始值吗？默认就是显示如：2019-12-03 至 2019-12-31这样？
> 
> 对，页面显示的就是2019年12月3号到12月31号，这段区间是选中状态。

这个前些日子已经改了，加了两个属性。
